/*
 * File: app/view/LoginForm.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Login.view.LoginForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.loginform',

    requires: [
        'Login.view.LoginFormViewModel',
        'Ext.form.field.Text',
        'Ext.container.Container',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'loginform'
    },
    bodyPadding: 10,
    title: '',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'textfield',
            anchor: '100%',
            fieldLabel: '',
            labelAlign: 'right',
            name: 'email',
            emptyText: 'Email'
        },
        {
            xtype: 'textfield',
            anchor: '100%',
            fieldLabel: '',
            labelAlign: 'right',
            name: 'password',
            emptyText: 'Password'
        },
        {
            xtype: 'container',
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'container',
                    flex: 1
                },
                {
                    xtype: 'button',
                    padding: '10 30 10 30',
                    text: 'Login',
                    listeners: {
                        click: 'onButtonClick'
                    }
                },
                {
                    xtype: 'container',
                    flex: 1
                }
            ]
        }
    ],

    onButtonClick: function(button, e, eOpts) {
        this.login();
    },

    login: function() {
        this.mask('Logging In...');
        AERP.Ajax.request({
            url:'/LoginRequest',
            params:this.getValues(),
            success:function(reply){
                this.unmask();
                console.log(reply);
            },
            failure:function(){
                this.unmask();
            },
            scope:this
        });

    }

});