/*
 * File: app/view/JobHistoryViewModel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('JakeCI.view.JobHistoryViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.jobhistory',

    requires: [
        'Ext.data.Store',
        'Ext.data.field.Field',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Array'
    ],

    stores: {
        HistoryStore: {
            pageSize: 10,
            fields: [
                {
                    name: 'buildNumber'
                }
            ],
            proxy: {
                type: 'ajax',
                noCache: false,
                simpleSortMode: true,
                url: 'History/getAllHistoryForJob',
                actionMethods: {
                    create: 'POST',
                    read: 'POST',
                    update: 'POST',
                    destroy: 'POST'
                },
                reader: {
                    type: 'array',
                    rootProperty: 'data',
                    totalProperty: 'total'
                }
            }
        }
    }

});