/*
 * File: app/view/JobHistory.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('JakeCI.view.JobHistory', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.jobhistory',

    requires: [
        'JakeCI.view.JobHistoryViewModel',
        'Ext.grid.Panel',
        'Ext.toolbar.Paging',
        'Ext.grid.column.Column',
        'Ext.view.Table',
        'Ext.form.Panel',
        'Ext.form.field.TextArea'
    ],

    viewModel: {
        type: 'jobhistory'
    },
    height: 614,
    width: 953,
    title: 'Build History',

    layout: {
        type: 'hbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'gridpanel',
            flex: 1,
            title: '',
            bind: {
                store: '{HistoryStore}'
            },
            dockedItems: [
                {
                    xtype: 'pagingtoolbar',
                    dock: 'top',
                    width: 360,
                    displayInfo: true,
                    bind: {
                        store: '{HistoryStore}'
                    }
                }
            ],
            columns: [
                {
                    xtype: 'gridcolumn',
                    width: 67,
                    dataIndex: 'buildNumber',
                    text: 'Build #'
                }
            ]
        },
        {
            xtype: 'form',
            flex: 1,
            height: 1122,
            width: 819,
            layout: 'fit',
            bodyPadding: 10,
            title: 'Build #',
            items: [
                {
                    xtype: 'textareafield',
                    fieldLabel: '',
                    readOnly: true
                }
            ]
        }
    ],

    getAllHistory: function(job) {
        var historyStore = this.lookupViewModel().getStore('HistoryStore');
        historyStore.getProxy().setExtraParams({
            job:job
        });
        historyStore.load({callback:function(records,operation,success){

        }});
    }

});